artistica/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^music/', include('musics.urls')),
]

musics/urls.py
from django.conf.urls import url
from . import views

app_name = "music"

urlpatterns = [
    # /musics/
    url(r'^$', views.index, name='index'),

    # /musics/1002
    url(r'^(?P<album_id>[0-9]+)/$', views.details, name='details'),
]

musics/models.py
from django.db import models


class Album(models.Model):
    class Meta:
        db_table = "musics"

    artist = models.CharField(max_length=100)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=250)

    def __str__(self):
        return self.album_title + " - " + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=50)
    song_title = models.CharField(max_length=250)

    def __str__(self):
        return self.song_title + "." + self.file_type

# Create your models here.

musics/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Album
# from django.template import loader
from django.http import Http404


def index(request):
    all_albums = Album.objects.all()
    return render(request, 'musics/index.html', {'all_albums': all_albums})
# Create your views here.


def details(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'musics/detail.html', {'album': album})

musics/templates/musics/detail.html
<h1> {{ album.album_title }}</h1>

<h2> {{ album.artist }}</h2>
<h3> {{ album.genre }}</h3>
<ul>
    {%  for song in album.song_set.all %}
    <li>{{ song.file_type }}  -  {{ song.song_title }}</li>
    {% endfor %}
</ul>

musics/templates/musics/index.html
{% if all_albums %}
    <ul>
        {% for album in all_albums %}
            <li> <a href="{% url 'music:details' album.id %}"> {{album.album_title}} - {{ album.artist }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3> You don't have any musics yet!!</h3>
{% endif %}